**import packages**

In [1]:
import pandas as pd
import numpy as np
import xgboost as xgb

**note that label column in the labels file was concatenated to feature file**

In [2]:
dfo = pd.read_excel('D:/Work&Study/Competetions/Vodafon/Tasks/Task1/feature.xlsx',sheet_name='feature')
df=dfo.iloc[1:515]
df

,Unnamed: 0,count,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132
1,2015-05-03 00:00:00,0,0,0,0,1,504,0,2,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,2015-05-04 00:00:00,0,0,0,0,0,2250,0,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,2015-05-05 00:00:00,0,0,0,0,0,1700,0,2,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,2015-05-06 00:00:00,0,0,0,0,0,2261,0,10,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
5,2015-05-07 00:00:00,0,0,0,0,0,2950,0,5,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,2016-10-01 00:00:00,0,0,0,0,0,4,0,2,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
511,2016-10-02 00:00:00,0,0,0,0,0,13,0,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
512,2016-10-03 00:00:00,0,0,0,0,0,15,0,1,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
513,2016-10-04 00:00:00,0,0,0,0,1,12,0,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
514,2016-10-05 00:00:00,0,0,0,0,0,1,0,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

# Preprocess the data and transform objects to categorical data then apply hot one encoding transformation

In [3]:
df.isnull().sum()

Unnamed: 0        0
count             0
Unnamed: 2        0
Unnamed: 3        0
Unnamed: 4        0
               ...
Unnamed: 128    468
Unnamed: 129    464
Unnamed: 130    386
Unnamed: 131    514
Unnamed: 132      0
Length: 133, dtype: int64

In [4]:
df.dtypes

Unnamed: 0       object
count             int64
Unnamed: 2        int64
Unnamed: 3        int64
Unnamed: 4        int64
                 ...
Unnamed: 128    float64
Unnamed: 129    float64
Unnamed: 130    float64
Unnamed: 131    float64
Unnamed: 132     object
Length: 133, dtype: object

In [5]:
df['Unnamed: 132'].unique()

array([0, 1], dtype=object)

In [6]:
pd.get_dummies(df,df.columns[df.dtypes == 'object'])
df.columns[df.dtypes == 'object']

Index(['Unnamed: 0', 'Unnamed: 132'], dtype='object')

In [7]:
# Check For Unique Values of Each Column
for i in df.columns[df.dtypes == 'object']:
    print(i,"::",df[i].unique())

Unnamed: 0 :: [datetime.datetime(2015, 5, 3, 0, 0) datetime.datetime(2015, 5, 4, 0, 0)
 datetime.datetime(2015, 5, 5, 0, 0) datetime.datetime(2015, 5, 6, 0, 0)
 datetime.datetime(2015, 5, 7, 0, 0) datetime.datetime(2015, 5, 8, 0, 0)
 datetime.datetime(2015, 5, 9, 0, 0) datetime.datetime(2015, 5, 10, 0, 0)
 datetime.datetime(2015, 5, 11, 0, 0) datetime.datetime(2015, 5, 12, 0, 0)
 datetime.datetime(2015, 5, 13, 0, 0) datetime.datetime(2015, 5, 14, 0, 0)
 datetime.datetime(2015, 5, 15, 0, 0) datetime.datetime(2015, 5, 16, 0, 0)
 datetime.datetime(2015, 5, 17, 0, 0) datetime.datetime(2015, 5, 18, 0, 0)
 datetime.datetime(2015, 5, 19, 0, 0) datetime.datetime(2015, 5, 20, 0, 0)
 datetime.datetime(2015, 5, 21, 0, 0) datetime.datetime(2015, 5, 22, 0, 0)
 datetime.datetime(2015, 5, 23, 0, 0) datetime.datetime(2015, 5, 24, 0, 0)
 datetime.datetime(2015, 5, 25, 0, 0) datetime.datetime(2015, 5, 26, 0, 0)
 datetime.datetime(2015, 5, 27, 0, 0) datetime.datetime(2015, 5, 28, 0, 0)
 datetime.datetime(2015, 5, 29, 0, 0) datetime.datetime(2015, 5, 30, 0, 0)
 datetime.datetime(2015, 6, 2, 0, 0) datetime.datetime(2015, 6, 3, 0, 0)
 datetime.datetime(2015, 6, 4, 0, 0) datetime.datetime(2015, 6, 5, 0, 0)
 datetime.datetime(2015, 6, 6, 0, 0) datetime.datetime(2015, 6, 7, 0, 0)
 datetime.datetime(2015, 6, 8, 0, 0) datetime.datetime(2015, 6, 9, 0, 0)
 datetime.datetime(2015, 6, 10, 0, 0) datetime.datetime(2015, 6, 11, 0, 0)
 datetime.datetime(2015, 6, 12, 0, 0) datetime.datetime(2015, 6, 13, 0, 0)
 datetime.datetime(2015, 6, 14, 0, 0) datetime.datetime(2015, 6, 15, 0, 0)
 datetime.datetime(2015, 6, 16, 0, 0) datetime.datetime(2015, 6, 17, 0, 0)
 datetime.datetime(2015, 6, 18, 0, 0) datetime.datetime(2015, 6, 19, 0, 0)
 datetime.datetime(2015, 6, 20, 0, 0) datetime.datetime(2015, 6, 21, 0, 0)
 datetime.datetime(2015, 6, 22, 0, 0) datetime.datetime(2015, 6, 23, 0, 0)
 datetime.datetime(2015, 6, 24, 0, 0) datetime.datetime(2015, 6, 25, 0, 0)
 datetime.datetime(2015, 6, 26, 0, 0) datetime.datetime(2015, 6, 27, 0, 0)
 datetime.datetime(2015, 6, 28, 0, 0) datetime.datetime(2015, 6, 29, 0, 0)
 datetime.datetime(2015, 6, 30, 0, 0) datetime.datetime(2015, 7, 1, 0, 0)
 datetime.datetime(2015, 7, 2, 0, 0) datetime.datetime(2015, 7, 3, 0, 0)
 datetime.datetime(2015, 7, 4, 0, 0) datetime.datetime(2015, 7, 5, 0, 0)
 datetime.datetime(2015, 7, 6, 0, 0) datetime.datetime(2015, 7, 7, 0, 0)
 datetime.datetime(2015, 7, 8, 0, 0) datetime.datetime(2015, 7, 9, 0, 0)
 datetime.datetime(2015, 7, 10, 0, 0) datetime.datetime(2015, 7, 11, 0, 0)
 datetime.datetime(2015, 7, 12, 0, 0) datetime.datetime(2015, 7, 13, 0, 0)
 datetime.datetime(2015, 7, 14, 0, 0) datetime.datetime(2015, 7, 15, 0, 0)
 datetime.datetime(2015, 7, 16, 0, 0) datetime.datetime(2015, 7, 17, 0, 0)
 datetime.datetime(2015, 7, 18, 0, 0) datetime.datetime(2015, 7, 19, 0, 0)
 datetime.datetime(2015, 7, 20, 0, 0) datetime.datetime(2015, 7, 21, 0, 0)
 datetime.datetime(2015, 7, 22, 0, 0) datetime.datetime(2015, 7, 23, 0, 0)
 datetime.datetime(2015, 7, 24, 0, 0) datetime.datetime(2015, 7, 25, 0, 0)
 datetime.datetime(2015, 7, 26, 0, 0) datetime.datetime(2015, 7, 27, 0, 0)
 datetime.datetime(2015, 7, 28, 0, 0) datetime.datetime(2015, 7, 29, 0, 0)
 datetime.datetime(2015, 7, 30, 0, 0) datetime.datetime(2015, 7, 31, 0, 0)
 datetime.datetime(2015, 8, 1, 0, 0) datetime.datetime(2015, 8, 2, 0, 0)
 datetime.datetime(2015, 8, 3, 0, 0) datetime.datetime(2015, 8, 4, 0, 0)
 datetime.datetime(2015, 8, 5, 0, 0) datetime.datetime(2015, 8, 6, 0, 0)
 datetime.datetime(2015, 8, 7, 0, 0) datetime.datetime(2015, 8, 8, 0, 0)
 datetime.datetime(2015, 8, 9, 0, 0) datetime.datetime(2015, 8, 10, 0, 0)
 datetime.datetime(2015, 8, 11, 0, 0) datetime.datetime(2015, 8, 12, 0, 0)
 datetime.datetime(2015, 8, 13, 0, 0) datetime.datetime(2015, 8, 14, 0, 0)
 datetime.datetime(2015, 8, 15, 0, 0) datetime.datetime(2015, 8, 16, 0, 0)
 datetime.datetime(2015, 8, 17, 0, 0) datetime.datetime(2015, 8, 18, 0, 0)
 datetime.datetime(2015, 8, 19, 0, 0) datetime.datetime(2015, 8, 20, 0, 0)
 datetime.datetime(2015, 8, 21, 0, 0) datetime.datetime(2015, 8, 22, 0, 0)
 datetime.datetime(2015, 8, 23, 0, 0) datetime.datetime(2015, 8, 24, 0, 0)
 datetime.datetime(2015, 8, 25, 0, 0) datetime.datetime(2015, 8, 26, 0, 0)
 datetime.datetime(2015, 8, 27, 0, 0) datetime.datetime(2015, 8, 28, 0, 0)
 datetime.datetime(2015, 8, 29, 0, 0) datetime.datetime(2015, 8, 30, 0, 0)
 datetime.datetime(2015, 8, 31, 0, 0) datetime.datetime(2015, 9, 1, 0, 0)
 datetime.datetime(2015, 9, 2, 0, 0) datetime.datetime(2015, 9, 3, 0, 0)
 datetime.datetime(2015, 9, 4, 0, 0) datetime.datetime(2015, 9, 5, 0, 0)
 datetime.datetime(2015, 9, 6, 0, 0) datetime.datetime(2015, 9, 7, 0, 0)
 datetime.datetime(2015, 9, 8, 0, 0) datetime.datetime(2015, 9, 9, 0, 0)
 datetime.datetime(2015, 9, 10, 0, 0) datetime.datetime(2015, 9, 11, 0, 0)
 datetime.datetime(2015, 9, 12, 0, 0) datetime.datetime(2015, 9, 13, 0, 0)
 datetime.datetime(2015, 9, 14, 0, 0) datetime.datetime(2015, 9, 15, 0, 0)
 datetime.datetime(2015, 9, 16, 0, 0) datetime.datetime(2015, 9, 17, 0, 0)
 datetime.datetime(2015, 9, 18, 0, 0) datetime.datetime(2015, 9, 19, 0, 0)
 datetime.datetime(2015, 9, 20, 0, 0) datetime.datetime(2015, 9, 21, 0, 0)
 datetime.datetime(2015, 9, 22, 0, 0) datetime.datetime(2015, 9, 23, 0, 0)
 datetime.datetime(2015, 9, 24, 0, 0) datetime.datetime(2015, 9, 25, 0, 0)
 datetime.datetime(2015, 9, 26, 0, 0) datetime.datetime(2015, 9, 27, 0, 0)
 datetime.datetime(2015, 9, 28, 0, 0) datetime.datetime(2015, 9, 29, 0, 0)
 datetime.datetime(2015, 9, 30, 0, 0) datetime.datetime(2015, 10, 1, 0, 0)
 datetime.datetime(2015, 10, 2, 0, 0) datetime.datetime(2015, 10, 3, 0, 0)
 datetime.datetime(2015, 10, 4, 0, 0) datetime.datetime(2015, 10, 5, 0, 0)
 datetime.datetime(2015, 10, 6, 0, 0) datetime.datetime(2015, 10, 7, 0, 0)
 datetime.datetime(2015, 10, 8, 0, 0) datetime.datetime(2015, 10, 9, 0, 0)
 datetime.datetime(2015, 10, 10, 0, 0)
 datetime.datetime(2015, 10, 11, 0, 0)
 datetime.datetime(2015, 10, 12, 0, 0)
 datetime.datetime(2015, 10, 13, 0, 0)
 datetime.datetime(2015, 10, 14, 0, 0)
 datetime.datetime(2015, 10, 15, 0, 0)
 datetime.datetime(2015, 10, 16, 0, 0)
 datetime.datetime(2015, 10, 17, 0, 0)
 datetime.datetime(2015, 10, 18, 0, 0)
 datetime.datetime(2015, 10, 19, 0, 0)
 datetime.datetime(2015, 10, 20, 0, 0)
 datetime.datetime(2015, 10, 21, 0, 0)
 datetime.datetime(2015, 10, 22, 0, 0)
 datetime.datetime(2015, 10, 23, 0, 0)
 datetime.datetime(2015, 10, 24, 0, 0)
 datetime.datetime(2015, 10, 25, 0, 0)
 datetime.datetime(2015, 10, 26, 0, 0)
 datetime.datetime(2015, 10, 27, 0, 0)
 datetime.datetime(2015, 10, 28, 0, 0)
 datetime.datetime(2015, 10, 29, 0, 0)
 datetime.datetime(2015, 10, 30, 0, 0)
 datetime.datetime(2015, 10, 31, 0, 0)
 datetime.datetime(2015, 11, 1, 0, 0) datetime.datetime(2015, 11, 2, 0, 0)
 datetime.datetime(2015, 11, 3, 0, 0) datetime.datetime(2015, 11, 4, 0, 0)
 datetime.datetime(2015, 11, 5, 0, 0) datetime.datetime(2015, 11, 6, 0, 0)
 datetime.datetime(2015, 11, 7, 0, 0) datetime.datetime(2015, 11, 8, 0, 0)
 datetime.datetime(2015, 11, 9, 0, 0)
 datetime.datetime(2015, 11, 10, 0, 0)
 datetime.datetime(2015, 11, 11, 0, 0)
 datetime.datetime(2015, 11, 12, 0, 0)
 datetime.datetime(2015, 11, 13, 0, 0)
 datetime.datetime(2015, 11, 14, 0, 0)
 datetime.datetime(2015, 11, 15, 0, 0)
 datetime.datetime(2015, 11, 16, 0, 0)
 datetime.datetime(2015, 11, 17, 0, 0)
 datetime.datetime(2015, 11, 18, 0, 0)
 datetime.datetime(2015, 11, 19, 0, 0)
 datetime.datetime(2015, 11, 20, 0, 0)
 datetime.datetime(2015, 11, 21, 0, 0)
 datetime.datetime(2015, 11, 22, 0, 0)
 datetime.datetime(2015, 11, 23, 0, 0)
 datetime.datetime(2015, 11, 24, 0, 0)
 datetime.datetime(2015, 11, 25, 0, 0)
 datetime.datetime(2015, 11, 26, 0, 0)
 datetime.datetime(2015, 11, 27, 0, 0)
 datetime.datetime(2015, 11, 28, 0, 0)
 datetime.datetime(2015, 11, 29, 0, 0)
 datetime.datetime(2015, 11, 30, 0, 0)
 datetime.datetime(2015, 12, 1, 0, 0) datetime.datetime(2015, 12, 2, 0, 0)
 datetime.datetime(2015, 12, 3, 0, 0) datetime.datetime(2015, 12, 4, 0, 0)
 datetime.datetime(2015, 12, 5, 0, 0) datetime.datetime(2015, 12, 6, 0, 0)
 datetime.datetime(2015, 12, 7, 0, 0) datetime.datetime(2015, 12, 8, 0, 0)
 datetime.datetime(2015, 12, 9, 0, 0)
 datetime.datetime(2015, 12, 10, 0, 0)
 datetime.datetime(2015, 12, 11, 0, 0)
 datetime.datetime(2015, 12, 12, 0, 0)
 datetime.datetime(2015, 12, 13, 0, 0)
 datetime.datetime(2015, 12, 14, 0, 0)
 datetime.datetime(2015, 12, 15, 0, 0)
 datetime.datetime(2015, 12, 16, 0, 0)
 datetime.datetime(2015, 12, 17, 0, 0)
 datetime.datetime(2015, 12, 18, 0, 0)
 datetime.datetime(2015, 12, 19, 0, 0)
 datetime.datetime(2015, 12, 20, 0, 0)
 datetime.datetime(2015, 12, 21, 0, 0)
 datetime.datetime(2015, 12, 22, 0, 0)
 datetime.datetime(2015, 12, 23, 0, 0)
 datetime.datetime(2015, 12, 24, 0, 0)
 datetime.datetime(2015, 12, 25, 0, 0)
 datetime.datetime(2015, 12, 26, 0, 0)
 datetime.datetime(2015, 12, 27, 0, 0)
 datetime.datetime(2015, 12, 28, 0, 0)
 datetime.datetime(2015, 12, 29, 0, 0)
 datetime.datetime(2015, 12, 30, 0, 0)
 datetime.datetime(2015, 12, 31, 0, 0) datetime.datetime(2016, 1, 1, 0, 0)
 datetime.datetime(2016, 1, 2, 0, 0) datetime.datetime(2016, 1, 3, 0, 0)
 datetime.datetime(2016, 1, 4, 0, 0) datetime.datetime(2016, 1, 5, 0, 0)
 datetime.datetime(2016, 1, 6, 0, 0) datetime.datetime(2016, 1, 7, 0, 0)
 datetime.datetime(2016, 1, 8, 0, 0) datetime.datetime(2016, 1, 9, 0, 0)
 datetime.datetime(2016, 1, 10, 0, 0) datetime.datetime(2016, 1, 11, 0, 0)
 datetime.datetime(2016, 1, 12, 0, 0) datetime.datetime(2016, 1, 13, 0, 0)
 datetime.datetime(2016, 1, 14, 0, 0) datetime.datetime(2016, 1, 15, 0, 0)
 datetime.datetime(2016, 1, 16, 0, 0) datetime.datetime(2016, 1, 17, 0, 0)
 datetime.datetime(2016, 1, 18, 0, 0) datetime.datetime(2016, 1, 19, 0, 0)
 datetime.datetime(2016, 1, 20, 0, 0) datetime.datetime(2016, 1, 21, 0, 0)
 datetime.datetime(2016, 1, 22, 0, 0) datetime.datetime(2016, 1, 23, 0, 0)
 datetime.datetime(2016, 1, 24, 0, 0) datetime.datetime(2016, 1, 25, 0, 0)
 datetime.datetime(2016, 1, 26, 0, 0) datetime.datetime(2016, 1, 27, 0, 0)
 datetime.datetime(2016, 1, 28, 0, 0) datetime.datetime(2016, 1, 29, 0, 0)
 datetime.datetime(2016, 1, 30, 0, 0) datetime.datetime(2016, 1, 31, 0, 0)
 datetime.datetime(2016, 2, 1, 0, 0) datetime.datetime(2016, 2, 2, 0, 0)
 datetime.datetime(2016, 2, 3, 0, 0) datetime.datetime(2016, 2, 4, 0, 0)
 datetime.datetime(2016, 2, 5, 0, 0) datetime.datetime(2016, 2, 6, 0, 0)
 datetime.datetime(2016, 2, 7, 0, 0) datetime.datetime(2016, 2, 8, 0, 0)
 datetime.datetime(2016, 2, 9, 0, 0) datetime.datetime(2016, 2, 10, 0, 0)
 datetime.datetime(2016, 2, 11, 0, 0) datetime.datetime(2016, 2, 12, 0, 0)
 datetime.datetime(2016, 2, 13, 0, 0) datetime.datetime(2016, 2, 14, 0, 0)
 datetime.datetime(2016, 2, 15, 0, 0) datetime.datetime(2016, 2, 16, 0, 0)
 datetime.datetime(2016, 2, 17, 0, 0) datetime.datetime(2016, 2, 18, 0, 0)
 datetime.datetime(2016, 2, 19, 0, 0) datetime.datetime(2016, 2, 20, 0, 0)
 datetime.datetime(2016, 2, 21, 0, 0) datetime.datetime(2016, 2, 22, 0, 0)
 datetime.datetime(2016, 2, 23, 0, 0) datetime.datetime(2016, 2, 24, 0, 0)
 datetime.datetime(2016, 2, 25, 0, 0) datetime.datetime(2016, 2, 26, 0, 0)
 datetime.datetime(2016, 2, 27, 0, 0) datetime.datetime(2016, 2, 28, 0, 0)
 datetime.datetime(2016, 2, 29, 0, 0) datetime.datetime(2016, 3, 1, 0, 0)
 datetime.datetime(2016, 3, 2, 0, 0) datetime.datetime(2016, 3, 3, 0, 0)
 datetime.datetime(2016, 3, 4, 0, 0) datetime.datetime(2016, 3, 5, 0, 0)
 datetime.datetime(2016, 3, 6, 0, 0) datetime.datetime(2016, 3, 7, 0, 0)
 datetime.datetime(2016, 3, 8, 0, 0) datetime.datetime(2016, 3, 9, 0, 0)
 datetime.datetime(2016, 3, 10, 0, 0) datetime.datetime(2016, 3, 11, 0, 0)
 datetime.datetime(2016, 3, 12, 0, 0) datetime.datetime(2016, 3, 13, 0, 0)
 datetime.datetime(2016, 3, 14, 0, 0) datetime.datetime(2016, 3, 15, 0, 0)
 datetime.datetime(2016, 3, 16, 0, 0) datetime.datetime(2016, 3, 17, 0, 0)
 datetime.datetime(2016, 3, 18, 0, 0) datetime.datetime(2016, 3, 19, 0, 0)
 datetime.datetime(2016, 3, 20, 0, 0) datetime.datetime(2016, 3, 21, 0, 0)
 datetime.datetime(2016, 3, 22, 0, 0) datetime.datetime(2016, 3, 23, 0, 0)
 datetime.datetime(2016, 3, 24, 0, 0) datetime.datetime(2016, 3, 25, 0, 0)
 datetime.datetime(2016, 3, 26, 0, 0) datetime.datetime(2016, 3, 27, 0, 0)
 datetime.datetime(2016, 3, 28, 0, 0) datetime.datetime(2016, 3, 29, 0, 0)
 datetime.datetime(2016, 3, 30, 0, 0) datetime.datetime(2016, 3, 31, 0, 0)
 datetime.datetime(2016, 4, 1, 0, 0) datetime.datetime(2016, 4, 2, 0, 0)
 datetime.datetime(2016, 4, 3, 0, 0) datetime.datetime(2016, 4, 4, 0, 0)
 datetime.datetime(2016, 4, 5, 0, 0) datetime.datetime(2016, 4, 6, 0, 0)
 datetime.datetime(2016, 4, 7, 0, 0) datetime.datetime(2016, 4, 8, 0, 0)
 datetime.datetime(2016, 4, 9, 0, 0) datetime.datetime(2016, 4, 10, 0, 0)
 datetime.datetime(2016, 4, 11, 0, 0) datetime.datetime(2016, 4, 12, 0, 0)
 datetime.datetime(2016, 4, 13, 0, 0) datetime.datetime(2016, 4, 14, 0, 0)
 datetime.datetime(2016, 4, 15, 0, 0) datetime.datetime(2016, 4, 16, 0, 0)
 datetime.datetime(2016, 4, 17, 0, 0) datetime.datetime(2016, 4, 18, 0, 0)
 datetime.datetime(2016, 4, 19, 0, 0) datetime.datetime(2016, 4, 20, 0, 0)
 datetime.datetime(2016, 4, 21, 0, 0) datetime.datetime(2016, 4, 22, 0, 0)
 datetime.datetime(2016, 4, 23, 0, 0) datetime.datetime(2016, 4, 24, 0, 0)
 datetime.datetime(2016, 4, 25, 0, 0) datetime.datetime(2016, 4, 26, 0, 0)
 datetime.datetime(2016, 4, 27, 0, 0) datetime.datetime(2016, 4, 28, 0, 0)
 datetime.datetime(2016, 4, 29, 0, 0) datetime.datetime(2016, 4, 30, 0, 0)
 datetime.datetime(2016, 5, 1, 0, 0) datetime.datetime(2016, 5, 2, 0, 0)
 datetime.datetime(2016, 5, 3, 0, 0) datetime.datetime(2016, 5, 4, 0, 0)
 datetime.datetime(2016, 5, 5, 0, 0) datetime.datetime(2016, 5, 6, 0, 0)
 datetime.datetime(2016, 5, 7, 0, 0) datetime.datetime(2016, 5, 8, 0, 0)
 datetime.datetime(2016, 5, 9, 0, 0) datetime.datetime(2016, 5, 10, 0, 0)
 datetime.datetime(2016, 5, 11, 0, 0) datetime.datetime(2016, 5, 12, 0, 0)
 datetime.datetime(2016, 5, 13, 0, 0) datetime.datetime(2016, 5, 14, 0, 0)
 datetime.datetime(2016, 5, 15, 0, 0) datetime.datetime(2016, 5, 16, 0, 0)
 datetime.datetime(2016, 5, 17, 0, 0) datetime.datetime(2016, 5, 18, 0, 0)
 datetime.datetime(2016, 5, 19, 0, 0) datetime.datetime(2016, 5, 20, 0, 0)
 datetime.datetime(2016, 5, 21, 0, 0) datetime.datetime(2016, 5, 22, 0, 0)
 datetime.datetime(2016, 5, 23, 0, 0) datetime.datetime(2016, 5, 24, 0, 0)
 datetime.datetime(2016, 5, 25, 0, 0) datetime.datetime(2016, 5, 26, 0, 0)
 datetime.datetime(2016, 5, 27, 0, 0) datetime.datetime(2016, 5, 28, 0, 0)
 datetime.datetime(2016, 5, 29, 0, 0) datetime.datetime(2016, 5, 30, 0, 0)
 datetime.datetime(2016, 5, 31, 0, 0) datetime.datetime(2016, 6, 1, 0, 0)
 datetime.datetime(2016, 6, 2, 0, 0) datetime.datetime(2016, 6, 3, 0, 0)
 datetime.datetime(2016, 6, 4, 0, 0) datetime.datetime(2016, 6, 5, 0, 0)
 datetime.datetime(2016, 6, 6, 0, 0) datetime.datetime(2016, 6, 7, 0, 0)
 datetime.datetime(2016, 6, 8, 0, 0) datetime.datetime(2016, 6, 9, 0, 0)
 datetime.datetime(2016, 6, 10, 0, 0) datetime.datetime(2016, 6, 11, 0, 0)
 datetime.datetime(2016, 6, 12, 0, 0) datetime.datetime(2016, 6, 13, 0, 0)
 datetime.datetime(2016, 6, 14, 0, 0) datetime.datetime(2016, 6, 15, 0, 0)
 datetime.datetime(2016, 6, 16, 0, 0) datetime.datetime(2016, 6, 17, 0, 0)
 datetime.datetime(2016, 6, 18, 0, 0) datetime.datetime(2016, 6, 19, 0, 0)
 datetime.datetime(2016, 6, 20, 0, 0) datetime.datetime(2016, 6, 21, 0, 0)
 datetime.datetime(2016, 6, 28, 0, 0) datetime.datetime(2016, 6, 29, 0, 0)
 datetime.datetime(2016, 6, 30, 0, 0) datetime.datetime(2016, 7, 1, 0, 0)
 datetime.datetime(2016, 7, 2, 0, 0) datetime.datetime(2016, 7, 3, 0, 0)
 datetime.datetime(2016, 7, 4, 0, 0) datetime.datetime(2016, 7, 5, 0, 0)
 datetime.datetime(2016, 7, 6, 0, 0) datetime.datetime(2016, 7, 7, 0, 0)
 datetime.datetime(2016, 7, 8, 0, 0) datetime.datetime(2016, 7, 9, 0, 0)
 datetime.datetime(2016, 7, 10, 0, 0) datetime.datetime(2016, 7, 11, 0, 0)
 datetime.datetime(2016, 7, 12, 0, 0) datetime.datetime(2016, 7, 13, 0, 0)
 datetime.datetime(2016, 7, 14, 0, 0) datetime.datetime(2016, 7, 15, 0, 0)
 datetime.datetime(2016, 7, 16, 0, 0) datetime.datetime(2016, 7, 17, 0, 0)
 datetime.datetime(2016, 7, 18, 0, 0) datetime.datetime(2016, 7, 19, 0, 0)
 datetime.datetime(2016, 7, 20, 0, 0) datetime.datetime(2016, 7, 21, 0, 0)
 datetime.datetime(2016, 7, 22, 0, 0) datetime.datetime(2016, 7, 23, 0, 0)
 datetime.datetime(2016, 7, 24, 0, 0) datetime.datetime(2016, 7, 25, 0, 0)
 datetime.datetime(2016, 7, 26, 0, 0) datetime.datetime(2016, 7, 27, 0, 0)
 datetime.datetime(2016, 7, 28, 0, 0) datetime.datetime(2016, 7, 29, 0, 0)
 datetime.datetime(2016, 7, 30, 0, 0) datetime.datetime(2016, 7, 31, 0, 0)
 datetime.datetime(2016, 8, 1, 0, 0) datetime.datetime(2016, 8, 2, 0, 0)
 datetime.datetime(2016, 8, 3, 0, 0) datetime.datetime(2016, 8, 4, 0, 0)
 datetime.datetime(2016, 8, 5, 0, 0) datetime.datetime(2016, 8, 6, 0, 0)
 datetime.datetime(2016, 8, 7, 0, 0) datetime.datetime(2016, 8, 8, 0, 0)
 datetime.datetime(2016, 8, 9, 0, 0) datetime.datetime(2016, 8, 10, 0, 0)
 datetime.datetime(2016, 8, 11, 0, 0) datetime.datetime(2016, 8, 12, 0, 0)
 datetime.datetime(2016, 8, 13, 0, 0) datetime.datetime(2016, 8, 14, 0, 0)
 datetime.datetime(2016, 8, 15, 0, 0) datetime.datetime(2016, 8, 16, 0, 0)
 datetime.datetime(2016, 8, 17, 0, 0) datetime.datetime(2016, 8, 18, 0, 0)
 datetime.datetime(2016, 8, 19, 0, 0) datetime.datetime(2016, 8, 20, 0, 0)
 datetime.datetime(2016, 8, 21, 0, 0) datetime.datetime(2016, 8, 22, 0, 0)
 datetime.datetime(2016, 8, 23, 0, 0) datetime.datetime(2016, 8, 24, 0, 0)
 datetime.datetime(2016, 8, 25, 0, 0) datetime.datetime(2016, 8, 26, 0, 0)
 datetime.datetime(2016, 8, 27, 0, 0) datetime.datetime(2016, 8, 28, 0, 0)
 datetime.datetime(2016, 8, 29, 0, 0) datetime.datetime(2016, 8, 30, 0, 0)
 datetime.datetime(2016, 8, 31, 0, 0) datetime.datetime(2016, 9, 1, 0, 0)
 datetime.datetime(2016, 9, 2, 0, 0) datetime.datetime(2016, 9, 3, 0, 0)
 datetime.datetime(2016, 9, 4, 0, 0) datetime.datetime(2016, 9, 5, 0, 0)
 datetime.datetime(2016, 9, 6, 0, 0) datetime.datetime(2016, 9, 7, 0, 0)
 datetime.datetime(2016, 9, 8, 0, 0) datetime.datetime(2016, 9, 9, 0, 0)
 datetime.datetime(2016, 9, 10, 0, 0) datetime.datetime(2016, 9, 11, 0, 0)
 datetime.datetime(2016, 9, 12, 0, 0) datetime.datetime(2016, 9, 13, 0, 0)
 datetime.datetime(2016, 9, 14, 0, 0) datetime.datetime(2016, 9, 15, 0, 0)
 datetime.datetime(2016, 9, 16, 0, 0) datetime.datetime(2016, 9, 17, 0, 0)
 datetime.datetime(2016, 9, 18, 0, 0) datetime.datetime(2016, 9, 19, 0, 0)
 datetime.datetime(2016, 9, 20, 0, 0) datetime.datetime(2016, 9, 21, 0, 0)
 datetime.datetime(2016, 9, 22, 0, 0) datetime.datetime(2016, 9, 23, 0, 0)
 datetime.datetime(2016, 9, 24, 0, 0) datetime.datetime(2016, 9, 25, 0, 0)
 datetime.datetime(2016, 9, 26, 0, 0) datetime.datetime(2016, 9, 27, 0, 0)
 datetime.datetime(2016, 9, 28, 0, 0) datetime.datetime(2016, 9, 29, 0, 0)
 datetime.datetime(2016, 9, 30, 0, 0) datetime.datetime(2016, 10, 1, 0, 0)
 datetime.datetime(2016, 10, 2, 0, 0) datetime.datetime(2016, 10, 3, 0, 0)
 datetime.datetime(2016, 10, 4, 0, 0) datetime.datetime(2016, 10, 5, 0, 0)]
Unnamed: 132 :: [0 1]

In [8]:
df2 = df
for i in df.columns[df.dtypes == 'object']:
    print(i,"::")
    df2[i] = df[i].astype('category')
    df2[i] = df2[i].cat.codes

Unnamed: 0 ::
Unnamed: 132 ::

c:\users\eng\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
c:\users\eng\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [9]:
df2.dtypes

Unnamed: 0        int16
count             int64
Unnamed: 2        int64
Unnamed: 3        int64
Unnamed: 4        int64
                 ...
Unnamed: 128    float64
Unnamed: 129    float64
Unnamed: 130    float64
Unnamed: 131    float64
Unnamed: 132       int8
Length: 133, dtype: object

In [10]:
df2.shape

(514, 133)

**split features from label column**

In [11]:
X= df2.iloc[:,0:132]

In [12]:
X.head()

,Unnamed: 0,count,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129,Unnamed: 130,Unnamed: 131
1,0,0,0,0,0,1,504,0,2,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,0,0,0,0,0,2250,0,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,0,0,0,0,0,1700,0,2,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,0,0,0,0,0,2261,0,10,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4,0,0,0,0,0,2950,0,5,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df2['Unnamed: 132'].unique()

array([0, 1], dtype=int64)

In [14]:
y=df2['Unnamed: 132']

**split data into training and test data**

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [17]:
X_train.shape

(411, 132)

**prepare an instance from XGB classifier to be trained on the data**

In [18]:
from sklearn.metrics import accuracy_score

In [19]:
xgb_classifier = xgb.XGBClassifier()

# Transform data into matrix form to be prepared for XGB

In [20]:
X_matrix = X.as_matrix()
y_matrix = y.as_matrix()
X_test_matrix=X_test.as_matrix()
xgb_classifier.fit(X_matrix,y_matrix)

c:\users\eng\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.
c:\users\eng\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.

c:\users\eng\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [21]:
predictions = xgb_classifier.predict(X_test_matrix)

In [22]:
predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [23]:
print("Accuracy of Model::",accuracy_score(y_test,predictions))

Accuracy of Model:: 0.9805825242718447

**Predict a single example**

In [24]:
print("Prediction By XGBoost::",xgb_classifier.predict(X_test.iloc[1])) # double square braces if we don`t want to transform to matrix

Prediction By XGBoost:: [0]

**Show features weight and the probability per each example**

In [25]:
import eli5
from eli5 import show_weights
show_weights(xgb_classifier)

Using TensorFlow backend.

In [26]:
eli5.show_prediction(xgb_classifier, X_test_matrix[1], show_feature_values=True)

# Start test samples prediction

In [27]:
dft=dfo[515:520]
dft=dft.iloc[:,0:132]
dft

,Unnamed: 0,count,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129,Unnamed: 130,Unnamed: 131
515,2016-10-06 00:00:00,0,0,0,0,0,9,0,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
516,2016-10-07 00:00:00,0,0,0,0,0,1,0,1,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
517,2016-10-08 00:00:00,0,0,0,0,0,1,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
518,2016-10-09 00:00:00,0,0,0,0,0,6,0,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
519,2016-10-10 00:00:00,0,1,0,0,1,37,0,7,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
dft2 = dft
for i in dft.columns[dft.dtypes == 'object']:
    print(i,"::")
    dft2[i] = dft[i].astype('category')
    dft2[i] = dft2[i].cat.codes

Unnamed: 0 ::

In [29]:
samples=dft2   
samples_matrix=samples.as_matrix()

c:\users\eng\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.

**Predict a single sample**

In [30]:
eli5.show_prediction(xgb_classifier, samples_matrix[4], show_feature_values=True)

# P(Y=1)

In [31]:
1-0.972

0.028000000000000025